/*
 * Author : Rinka
 * Date   : 2020/2/13
 */
package com.enkanrec.twitkitFridge.api.form;

import com.enkanrec.twitkitFridge.interceptor.MonitorInterceptor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.UUID;

/**
 * Class : BaseJsonWarp
 * Usage :
 */
@Slf4j
@ToString
@EqualsAndHashCode
public class BaseJsonWarp<InnerTy> implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * 从哪个外部服务发起的请求
     */
    @Getter
    @NotNull
    private String forwardFrom;

    /**
     * 请求的客户端时间戳（ISO8601）
     */
    @Getter
    @Setter
    @NotNull
    private String timestamp;

    /**
     * 请求的request id
     */
    @Getter
    private String taskId;

    /**
     * WebSocket模式下的命令所在模块名
     */
    @Getter
    @Setter
    private String of = null;

    /**
     * WebSocket模式下的命令参数
     */
    @Getter
    @Setter
    private String command = null;

    @Getter
    @Setter
    private InnerTy data;

    public void setTaskId(String requestId) {
        this.taskId = requestId;
        if (requestId == null) {
            requestId = "SELF_" + UUID.randomUUID().toString();
            log.warn("RequestId is not pass in, generated by fridge");
        }
        MDC.put(MonitorInterceptor.LOG_KEY_REQUEST_ID, requestId);
        log.info(String.format("Request id generated: %s", requestId));
    }

    public void setForwardFrom(String forwardFrom) {
        log.info(String.format("Request form built, forward from: %s", forwardFrom));
        this.forwardFrom = forwardFrom;
    }
}
