name: Fridge

on:
  push:
    branches:
      - dev
    paths:
      - 'fridge/fridge-src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file fridge/fridge-src/pom.xml -Dmaven.test.skip=true 
    - name: Moving builds to artifacts directory
      run: |
        mkdir -p artifacts/fridge
        cp fridge/fridge-src/target/*.jar artifacts/fridge
    - uses: actions/upload-artifact@v1
      with:
        name: fridge
        path: artifacts/fridge
